// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchConfig() {
  return window['go']['main']['App']['FetchConfig']();
}

export function GenerateKeyPair(arg1) {
  return window['go']['main']['App']['GenerateKeyPair'](arg1);
}

export function List(arg1) {
  return window['go']['main']['App']['List'](arg1);
}

export function RetrieveByUUID(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RetrieveByUUID'](arg1, arg2, arg3, arg4);
}

export function RetrieveSharedContent(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RetrieveSharedContent'](arg1, arg2, arg3, arg4, arg5);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function Share(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Share'](arg1, arg2, arg3, arg4);
}

export function StoreConfig(arg1) {
  return window['go']['main']['App']['StoreConfig'](arg1);
}

export function Upload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Upload'](arg1, arg2, arg3, arg4);
}
