// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateKeyPair(arg1) {
  return window['go']['main']['App']['GenerateKeyPair'](arg1);
}

export function List(arg1) {
  return window['go']['main']['App']['List'](arg1);
}

export function RetrieveByUUID(arg1, arg2, arg3) {
  return window['go']['main']['App']['RetrieveByUUID'](arg1, arg2, arg3);
}

export function RetrieveSharedContent(arg1, arg2, arg3) {
  return window['go']['main']['App']['RetrieveSharedContent'](arg1, arg2, arg3);
}

export function Share(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Share'](arg1, arg2, arg3, arg4);
}

export function Upload(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Upload'](arg1, arg2, arg3, arg4);
}
