estuary:
  base_api_url: "https://api.estuary.tech"
  download_api_url: "https://dweb.link/ipfs"
  shuttle_api_url: "https://shuttle-4.estuary.tech"
  token: "ESTad52ad4c-8c67-4ce5-b884-ffa408f65c0fARY"
email:
  server: "smtp.mailtrap.io"
  port: 2525
  username: "ac984e52bfd35d"
  password: "861b495c076713"
  from: "noreply@bond180.com"
stat:
  badgerdb:
    path: "badger.db"
